language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-2_zhbanova_labs
  - make -j
  - cd ./bin/
  - ./test_matrix
notifications:
  email: false
