language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-2_savosina_labs
  - make -j
  - ls
  -./set_test/test_tset
notifications:
  email: false
