language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-2_savosina_labs
  - cd ./bin/
  - ./settest/settest
  - ./gtest/gtest
notifications:
  email: false
